import { Injectable } from '@nestjs/common';
import { YoutubeSearchItem } from './youtube.types';

@Injectable()
export class YoutubeScorerService {
  /**
   * Hard-reject videos that are definitively the wrong thing.
   * These patterns are so reliably wrong that no score can save them.
   */
  isHardRejected(title: string): boolean {
    const t = title.toLowerCase();

    const HARD_REJECT_PATTERNS: RegExp[] = [
      // Audio gimmick versions
      /\b(lofi|lo-fi|lo\s+fi)\b/,
      /\b8\s*d\s*(audio|music)\b/,
      /\b4\s*d\s*(audio|music)\b/,
      /\b3\s*d\s*(audio|music)\b/,
      /\bslowed(\s*[\+&]\s*(reverb|bass\s*boost|reverbed?))?\b/,
      /\breverb(ed)?\b/,
      /\bbass\s*boost(ed)?\b/,
      /\bnightcore\b/,
      /\bsped[\s-]+up\b/,
      /\bpitch[\s-]*(shift|correct|perfect)\b/,
      /\b(only\s+)?headphones?\s+(only|required|recommended|version)\b/,
      /\bsurround\s*sound\b/,
      /\bbinaural\b/,
      /\basmr\b/,

      // Karaoke / instrumental
      /\bkaraoke\b/,
      /\binstrumental\b/,

      // Covers and tributes (NOT official)
      /\btribute\b/,
      /\bsoundalike\b/,

      // Dubbed / translated versions
      /\b(hindi|tamil|telugu|kannada|malayalam|punjabi|bengali|marathi|urdu)\s+(dubbed|version|cover)\b/i,
      /\bdubbed\b/,

      // Lyrics-only videos are poor playback candidates.
      /\blyrics?\s*(video|version)?\b/,

      // Compilations / jukebox
      /\bmegamix\b/,
      /\bnon[\s-]stop\b/,
      /\bjukebox\b/,
      /\bfull\s+album\b/,
      /\bplaylist\b/,
      /\btop\s+\d+\s+(songs?|tracks?|hits?)\b/,

      // Clearly live events (soft "live" handled in scoring)
      /\blive\s+(at|from|performance|concert|show)\b/,
      /\bconcert\s+(version|live|at)\b/,
      /\b\(live\)\b/,
      /\blive\s+session\b/,

      // Behind the scenes / making of
      /\b(behind\s+the\s+scenes|making\s+of)\b/,
    ];

    return HARD_REJECT_PATTERNS.some((p) => p.test(t));
  }

  scoreVideo(
    item: YoutubeSearchItem,
    normalizedArtist: string,
    normalizedTrack: string,
  ): number {
    const rawTitle = item.snippet?.title ?? '';
    const title = rawTitle.toLowerCase();
    const channel = item.snippet?.channelTitle?.toLowerCase() ?? '';

    let score = 0;

    // ── TIER 0: Track-title relevance ─────────────────────────────────────────
    // Hard gate: if none of the significant words from the requested track name
    // appear in the video title, it is the wrong song. Return immediately —
    // no channel trust bonus (Vevo +15, Topic +30) should ever override this.
    const significantTrackWords = normalizedTrack
      .split(/\s+/)
      .filter((w) => w.length > 2);
    const titleMentionsTrack =
      significantTrackWords.length === 0 ||
      significantTrackWords.some((w) => title.includes(w));
    if (!titleMentionsTrack) return -50;

    // ── TIER 1: Topic channels ────────────────────────────────────────────────
    // Auto-generated by YouTube from official distributor uploads.
    // Logic: Only boost if the Topic channel belongs to the requested artist.
    const isTopic =
      channel.endsWith(' - topic') ||
      channel === 'topic' ||
      channel.includes(' - topic');

    if (isTopic) {
      if (channel.includes(normalizedArtist)) {
        score += 30;
      } else {
        // Topic channel for a different artist? Highly likely to be the wrong song.
        score -= 15;
      }
    }

    // ── TIER 2: Vevo ──────────────────────────────────────────────────────────
    const isVevo = channel.includes('vevo');
    if (isVevo) score += 15;

    // ── TIER 2.5: Trusted Indian labels ───────────────────────────────────────
    const trustedIndianLabels = [
      't-series',
      'sony music india',
      'zee music',
      'speed records',
      'zee music company',
      'saregama',
      'tips official',
    ];
    const isIndianLabel = trustedIndianLabels.some((label) =>
      channel.includes(label),
    );
    if (isIndianLabel) score += 20;

    // ── TIER 3: Artist channel match ──────────────────────────────────────────
    if (channel.includes(normalizedArtist)) score += 10;
    if (title.includes(normalizedArtist)) score += 3;

    // ── TIER 4: Explicit official labels in title ──────────────────────────────
    // For a streaming app, clean official audio is the ideal format.
    // The gap must be wide enough to overcome channel-trust bonuses
    // (e.g. VEVO +15) when a genuine official audio exists elsewhere.

    if (title.includes('official audio')) {
      score += 15; // ideal format for streaming
    } else if (
      title.includes('official music video') ||
      title.includes('official video')
    ) {
      score += 8; // legitimate, but not ideal for audio streaming
    }

    // Extra nudge: explicitly labeled music videos are suboptimal for streaming
    if (title.includes('music video')) {
      score -= 3;
    }

    // Mild penalty for generic "audio" (non-official, often low quality)
    if (
      title.includes('audio') &&
      !title.includes('official') &&
      !title.includes('video')
    ) {
      score -= 2;
    }

    // ── TIER 5: Soft negatives ────────────────────────────────────────────────
    if (/\blive\b/.test(title) && !/live\s+(at|from|concert|session)/.test(title))
      score -= 4;

    if (/\bremix\b/.test(title)) score -= 5;

    if (/\bcover\b/.test(title) && !isTopic && !isVevo) score -= 8;

    if (/\b(acoustic|unplugged|stripped)\b/.test(title)) score -= 6;

    if (/\bfull\s+song\b/.test(title) && !isTopic && !isVevo && !isIndianLabel)
      score -= 3;

    return score;
  }
}
